#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
SUDO_CONFIG="sudo.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_APT="dotbot-apt"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git -C "${DOTBOT_APT}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_APT}"

# sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-apt -c "${SUDO_CONFIG}" "${@}"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
