sparklines:
    - title: CPU usage
      sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
textboxes:
    - title: Docker Stats
      rate-ms: 1000
      sample: docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.PIDs}}"
    - title: Services
      rate-ms: 1000
      sample: systemctl status rabbitmq-server | grep Active
